// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: ava_api.proto
#ifndef GRPC_ava_5fapi_2eproto__INCLUDED
#define GRPC_ava_5fapi_2eproto__INCLUDED

#include "ava_api.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace api {

class LecheMesCouilles GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status rapeagland(::grpc::ClientContext* context, const ::api::Plugin& request, ::api::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::Reply>> Asyncrapeagland(::grpc::ClientContext* context, const ::api::Plugin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::Reply>>(AsyncrapeaglandRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::Reply>* AsyncrapeaglandRaw(::grpc::ClientContext* context, const ::api::Plugin& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status rapeagland(::grpc::ClientContext* context, const ::api::Plugin& request, ::api::Reply* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::Reply>> Asyncrapeagland(::grpc::ClientContext* context, const ::api::Plugin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::Reply>>(AsyncrapeaglandRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::api::Reply>* AsyncrapeaglandRaw(::grpc::ClientContext* context, const ::api::Plugin& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_rapeagland_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status rapeagland(::grpc::ServerContext* context, const ::api::Plugin* request, ::api::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_rapeagland : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithAsyncMethod_rapeagland() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_rapeagland() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status rapeagland(::grpc::ServerContext* context, const ::api::Plugin* request, ::api::Reply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestrapeagland(::grpc::ServerContext* context, ::api::Plugin* request, ::grpc::ServerAsyncResponseWriter< ::api::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_rapeagland<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_rapeagland : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(Service *service) {}
   public:
    WithGenericMethod_rapeagland() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_rapeagland() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status rapeagland(::grpc::ServerContext* context, const ::api::Plugin* request, ::api::Reply* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace api


#endif  // GRPC_ava_5fapi_2eproto__INCLUDED
