// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: ava_api.proto

#include "ava_api.pb.h"
#include "ava_api.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace api {

static const char* LecheMesCouilles_method_names[] = {
  "/api.LecheMesCouilles/rapeagland",
};

std::unique_ptr< LecheMesCouilles::Stub> LecheMesCouilles::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< LecheMesCouilles::Stub> stub(new LecheMesCouilles::Stub(channel));
  return stub;
}

LecheMesCouilles::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_rapeagland_(LecheMesCouilles_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LecheMesCouilles::Stub::rapeagland(::grpc::ClientContext* context, const ::api::Plugin& request, ::api::Reply* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_rapeagland_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::api::Reply>* LecheMesCouilles::Stub::AsyncrapeaglandRaw(::grpc::ClientContext* context, const ::api::Plugin& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::api::Reply>(channel_.get(), cq, rpcmethod_rapeagland_, context, request);
}

LecheMesCouilles::Service::Service() {
  (void)LecheMesCouilles_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      LecheMesCouilles_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< LecheMesCouilles::Service, ::api::Plugin, ::api::Reply>(
          std::mem_fn(&LecheMesCouilles::Service::rapeagland), this)));
}

LecheMesCouilles::Service::~Service() {
}

::grpc::Status LecheMesCouilles::Service::rapeagland(::grpc::ServerContext* context, const ::api::Plugin* request, ::api::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace api

